# Generated by Django 5.1.4 on 2025-01-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='release_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
